# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_giveaway_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
